services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  registration-api:
    build:
      context: ./src/registration.presentation
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Username=appuser;Password=apppassword;Database=appdb"
      AppSettings__JWTSecret: "DEV_SUPER_SECRET_KEY_1234567891111"
    ports:
      - "5120:5120"

  registration-frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    depends_on:
      - registration-api
    ports:
      - "4200:4200"

volumes:
  pgdata:
