server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Обрабатываем все SPA маршруты
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Статика: JS, CSS, картинки
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {
        try_files $uri =404;
        expires 1y;
        access_log off;
    }
}
